"""Deterministic, idempotent Cypher projection."""

from __future__ import annotations

import datetime as dt
import json
import re
from pathlib import Path
from typing import Any

from .models import RegistryData
from .yaml_io import load_yaml


def _cypher_value(value: Any) -> str:
    if isinstance(value, (dt.date, dt.datetime)):
        value = value.isoformat()
    if isinstance(value, dict):
        value = json.dumps(value, default=lambda item: item.isoformat(), sort_keys=True)
    if isinstance(value, list):
        return "[" + ", ".join(_cypher_value(item) for item in value) + "]"
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return json.dumps(str(value), ensure_ascii=False)


def _property_map(properties: dict[str, Any]) -> str:
    return ", ".join(
        f"{key}: {_cypher_value(value)}"
        for key, value in sorted(properties.items())
        if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", key)
    )


def export_neo4j(
    registry: RegistryData,
    destination: Path,
    root: Path,
    registry_version: str,
    schema_version: str,
) -> list[Path]:
    destination.mkdir(parents=True, exist_ok=True)
    constraints = destination / "constraints.cypher"
    constraints.write_text(
        "CREATE CONSTRAINT named_entity_id IF NOT EXISTS\n"
        "FOR (n:NamedEntity) REQUIRE n.entity_id IS UNIQUE;\n\n"
        "CREATE CONSTRAINT platform_participation_id IF NOT EXISTS\n"
        "FOR (p:PlatformParticipation) REQUIRE p.participation_id IS UNIQUE;\n\n"
        "CREATE INDEX named_entity_preferred_name IF NOT EXISTS\n"
        "FOR (n:NamedEntity) ON (n.preferred_name);\n",
        encoding="utf-8",
    )
    mapping_raw = load_yaml(root / "mappings" / "neo4j_mapping.yaml")
    mapping = mapping_raw if isinstance(mapping_raw, dict) else {}
    labels = mapping.get("entity_labels", {})
    lines = [
        "// Generated by PHNER. Re-running this file is idempotent.",
        f"// Registry version: {registry_version}; schema version: {schema_version}",
        "",
    ]
    for record in sorted(registry.records_of_type("entity"), key=lambda item: item.identifier):
        data = record.data
        secondary = labels.get(data.get("entity_type"), "Other")
        properties = {
            "entity_id": data.get("entity_id"),
            "preferred_name": data.get("preferred_name"),
            "entity_type": data.get("entity_type"),
            "status": data.get("status"),
            "valid_from": data.get("valid_from"),
            "valid_to": data.get("valid_to"),
            "aliases": [
                item.get("value")
                for item in data.get("names", [])
                if isinstance(item, dict) and item.get("value")
            ],
            "classifications": data.get("classifications", []),
            "registry_version": registry_version,
            "schema_version": schema_version,
            "last_reviewed": (data.get("curation") or {}).get("last_reviewed"),
        }
        lines.append(
            f"MERGE (n:NamedEntity:{secondary} {{entity_id: {_cypher_value(record.identifier)}}})"
        )
        lines.append(f"SET n += {{{_property_map(properties)}}};")
    relationships = sorted(
        registry.records_of_type("relationship"), key=lambda item: item.identifier
    )
    for record in relationships:
        data = record.data
        rel_type = str(data.get("relationship_type"))
        subject_value = _cypher_value(data.get("subject_entity_id"))
        object_value = _cypher_value(data.get("object_entity_id"))
        relationship_value = _cypher_value(record.identifier)
        properties = {
            "relationship_id": record.identifier,
            "assertion_status": (data.get("curation") or {}).get("assertion_status"),
            "valid_from": data.get("valid_from"),
            "valid_to": data.get("valid_to"),
            "registry_version": registry_version,
        }
        lines.extend(
            [
                f"MATCH (s:NamedEntity {{entity_id: {subject_value}}})",
                f"MATCH (o:NamedEntity {{entity_id: {object_value}}})",
                f"MERGE (s)-[r:{rel_type} {{relationship_id: {relationship_value}}}]->(o)",
                f"SET r += {{{_property_map(properties)}}};",
            ]
        )
    participations = sorted(
        registry.records_of_type("participation"), key=lambda item: item.identifier
    )
    for record in participations:
        data = record.data
        participation_value = _cypher_value(record.identifier)
        entity_value = _cypher_value(data.get("entity_id"))
        platform_value = _cypher_value(data.get("platform_entity_id"))
        properties = {
            "participation_id": record.identifier,
            "lifecycle_status": data.get("lifecycle_status"),
            "roles": data.get("roles", []),
            "environments": data.get("environments", []),
            "data_exchange_modes": data.get("data_exchange_modes", []),
            "valid_from": data.get("valid_from"),
            "valid_to": data.get("valid_to"),
            "registry_version": registry_version,
        }
        lines.extend(
            [
                f"MERGE (p:PlatformParticipation {{participation_id: {participation_value}}})",
                f"SET p += {{{_property_map(properties)}}}",
                "WITH p",
                f"MATCH (e:NamedEntity {{entity_id: {entity_value}}})",
                f"MATCH (platform:NamedEntity:Platform {{entity_id: {platform_value}}})",
                "MERGE (e)-[:HAS_PLATFORM_PARTICIPATION]->(p)",
                "MERGE (p)-[:WITH_PLATFORM]->(platform);",
            ]
        )
    output = destination / "import.cypher"
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return [constraints, output]
